sids:
  hogwarts: hogwarts
authenticationMode: 1
loginUIUsernameTxt: 'Username LDAP notice text'
loginUIPasswordTxt: 'Password LDAP notice text'
ldapUserHelpLinkUrl: 'http://www.example.com/'
ldapUserHelpLinkText: 'LDAP help link description text'
emailOption: 3
emailUpdate: 1
passwordOption: 2
allowOnlyIfTextInDn: {  }
excludeIfTextInDn: {  }
excludeIfNoAuthorizations: 0
ssoRemoteUserStripDomainName: 1
ssoExcludedPaths:
  - '<front>'
ssoExcludedHosts:
seamlessLogin: '0'
ldapImplementation: mod_auth_sspi
cookieExpire: '-1'
emailTemplateHandling: if_empty
emailTemplate: '@username@example.com'
emailTemplateUsageResolveConflict: true
emailTemplateUsageNeverUpdate: true
emailTemplateUsagePromptUser: true
emailTemplateUsageRedirectOnLogin: false
emailTemplateUsagePromptRegex: '.*@hogwarts\.edu'
